name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install yarn dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          build: yarn build
          start: yarn start

      - name: Upload failed test screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: upload screenshots
          # ./blank_artifact.txt to maintain directory structure
          # https://github.com/actions/upload-artifact/issues/174
          path: |
            ./blank_artifact.txt
            ./cypress/screenshots
